### PR TITLE
v0.14.4 upgrade

### PR DESCRIPTION
**Pull request by spkane**
This gets the code compiling with the newest terraform libraries. 

In general it appears to create the local file properly, but I could not actually get terraform to respect the lock with a local state file.

Might try to test it with S3 and Dynamo DB when I get a moment. My guess it that there is now a bit more logic on determining wether the lock file is still valid.

### CODE REVIEW

**Comment by jaredledvina** [comment]
@spkane - Just curious if you knew of any work left here. I tested this with a rather simple S3 and DnyamoDB lock setup and it seems to work. I'd be interested in helping if I can.

**Comment by spkane** [comment]
@jaredledvina As far as I know this did the job, but that work was all the time I had to spend on it. I think this project is dead, but this could be merged in if indeed it is both complining and working with current releases.

**Comment by jaredledvina** [comment]
Ah great, yeah worked for me with the S3 state and DynamoDB lock setup on 0.14.10 on Friday actually. 

@minamijoyo if you happen to still maintain this, it'd be great to see it merged in and I'm happy to help test it further if you would like to see anything specifically verified. Thanks for the project!

**Review by minamijoyo — APPROVED** [review]
LGTM 👍

**Comment by minamijoyo** [comment]
@spkane @jaredledvina Thank you for your work.

@jaredledvina Could you share you use-case if possible? Because I originally wrote the tflock for refactoring, but now I'm using the [tfmigrate](https://github.com/minamijoyo/tfmigrate) for it. I'm just curious when the tflock useful.

**Pull request merged**
